### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nicholasrodriguez** [device42/ansible_lookup_plugin#1]
Hi @achmykhalo,

Great lookup module, thanks!

Is there any chance this could be extended so that the D42 instance, D42 pw and D42 username can be passed in as variables as per below rather than just sourced from environment variables?

ansible-playbook -i inventories/ playbook.yaml -e "D42_PWD=<password>, D42_URL=<url>, D42_USER=<username>"

Going even further could it prompt for the D42 password?

Having the D42 password in environment variables or history isn't ideal from a security perspective.

Regards,

Nick

**Comment by ghost** [comment]
Hello @nicholasrodriguez, 

thanks for the feedback, we will investigate the possibility of adding this feature.
Keep you posted here.

**Comment by nicholasrodriguez** [comment]
@achmykhalo thanks for looking at this.

Having discussed this with some of our platform teams ideally the D42 details would be prompted for therefore we wouldn't see the password in history or the logs.

In addtion the username could still be prompted but have the default of the currently logged in user (perhaps sourced from env in Linux) which would be useful.

**Comment by ghost** [comment]
@nicholasrodriguez we accepted this feature request, will try to implement it in the near future. Thanks.

**Comment by ghost** [comment]
Hello @nicholasrodriguez , I've sent commit with the prompt feature, please take a look `d42_prompt.py` and `example_playbook_prompt.yaml`.
Please write feedback, and if all good we may close this feature request.
Regards.

**Comment by nicholasrodriguez** [comment]
Hi @achmykhalo this looks great. I should be able to test it by Monday. I'll update this feature request with the results.
Regards

**Comment by ghost** [comment]
hi @nicholasrodriguez, did you have a chance to test?

**Comment by nicholasrodriguez** [comment]
@achmykhalo  I should be able to test this tomorrow. I'll let you know how this goes.

**Comment by nicholasrodriguez** [comment]
I've run a test using Ansible 2.7 and I get the following error;

```
{"msg": "An unhandled exception occurred while running the lookup plugin 'd42_prompt'. Error was a <type 'exceptions.IndexError'>, original message: list index out of range"}
```

**Comment by ghost** [comment]
Did you use a new "yaml" file for the prompt? It also changed.

**Comment by nicholasrodriguez** [comment]
Nope, I've just realised the playbook needs some additional parameters. I'll do that now

**Comment by nicholasrodriguez** [comment]
Hi @achmykhalo this is working with small test playbooks I have.

I need to test this functionality with production playbooks which will take time to get updated or refactored with the new functionality. I'll let you know how that goes.

**Comment by ghost** [comment]
@nicholasrodriguez 👍

**Comment by ghost** [comment]
@nicholasrodriguez I close the issue if you will have any problems in future, feel free to re-open. Thank you.
